platform :ios,'7.0'

#pod 'ShareThis', '~> 1.0.0'
pod 'MagicalRecord', '~> 2.1'
pod 'JASidePanels', '~> 1.3.2'
pod 'CocoaLumberjack', '1.6.2'
pod 'XCDYouTubeVideoPlayerViewController', '~> 1.1.1'
pod 'IDMPhotoBrowser', '~> 1.2.4'
pod 'REFrostedViewController', '~> 2.3'